// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ijvglfylhubgbsdczqct.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqdmdsZnlsaHViZ2JzZGN6cWN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NDM2MDYsImV4cCI6MjA2NzIxOTYwNn0.HvcgPlp7lQZpOE24dysDfVhTkl8z2BWbnjcxhMgooVQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});